BOARD_SIZE = 13
INF = 9999
BOMB_TIMER = 7

TILE_GRASS = 0
TILE_WALL = 1
TILE_BOX = 2
TILE_RADIUS = 3
TILE_CAPACITY = 4

A_STOP = 0
A_LEFT = 1
A_RIGHT = 2
A_UP = 3
A_DOWN = 4
A_BOMB = 5

DIRS = {
    A_STOP: (0, 0),
    A_LEFT: (-1, 0),
    A_RIGHT: (1, 0),
    A_UP: (0, -1),
    A_DOWN: (0, 1),
}

BLAST_DIRS = [(1, 0), (-1, 0), (0, 1), (0, -1)]
MOVE_ACTIONS = [A_LEFT, A_RIGHT, A_UP, A_DOWN]
ALL_ACTIONS = [A_STOP, A_LEFT, A_RIGHT, A_UP, A_DOWN, A_BOMB]

MAX_BFS_SAFE = 12
MAX_BFS_ESCAPE = 8
MAX_BFS_ITEM = 10
MAX_BFS_TARGET = 10
MAX_BFS_ENEMY = 8
MAX_FUTURE_DEPTH = 5
MAX_ENEMY_ESCAPE_SIM = 7

INVALID_SCORE = -1e9

CURRENT_DANGER_ESCAPE_THRESHOLD = 4
ACTION_ESCAPE_LOOKAHEAD = 8
MIN_SAFE_CELLS_AFTER_BOMB = 5

SAFE_TILE_BONUS = 120
NEAR_DANGER_PENALTY = 1200
ESCAPE_IMPROVEMENT_BONUS = 650
MOBILITY_WEIGHT = 45
OPEN_CELL_BONUS = 80
CORRIDOR_PENALTY = 45
DEAD_END_PENALTY = 260
FUTURE_SURVIVAL_WEIGHT = 0.9
STOP_BASE_PENALTY = 45
STOP_IN_DANGER_PENALTY = 1200
RECENT_POSITION_PENALTY = 35
STUCK_NEW_CELL_BONUS = 130
STUCK_RECENT_POSITION_PENALTY = 95

BOMB_BASE_BOX_BONUS = 320
BOMB_BOX_WEIGHT = 150
BOMB_MULTI_BOX_WEIGHT = 65
BOMB_FRONTIER_WEIGHT = 55
BOMB_ENEMY_HIT_WEIGHT = 520
BOMB_ENEMY_PRESSURE_WEIGHT = 0.35
BOMB_DEAD_END_PENALTY = 380
BOMB_LOW_SAFE_SPACE_PENALTY = 900
BOMB_NO_VALUE_PENALTY = 900
BOMB_RECENT_AREA_PENALTY = 450
BOMB_STUCK_BOX_BONUS = 220

ITEM_TARGET_BONUS = 180
BOX_TARGET_BONUS = 155
FRONTIER_TARGET_BONUS = 135
CENTER_CONTROL_BONUS = 75
ENEMY_PRESSURE_TARGET_BONUS = 90
RL_WEIGHT = 0.20

TENSOR_ITEM_WEIGHT = 190.0
TENSOR_FRONTIER_WEIGHT = 150.0
TENSOR_MOBILITY_WEIGHT = 85.0
TENSOR_CENTER_WEIGHT = 55.0
TENSOR_DANGER_WEIGHT = 520.0
TENSOR_DEADEND_WEIGHT = 240.0
